spring:
  datasource:
    url: jdbc:mysql://localhost:3306/relove_cart_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: relove-cart-service
server:
  port: 9090

test:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect