spring:
  datasource:
    url: jdbc:mysql://localhost:3306/relove_cart_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: relove-cart-service
server:
  port: 9090
